spring:
  application:
     name: TelegramBotForMarketTest

  datasource:
    password: ${DB_PASSWORD}
    username: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/telegrambot
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true